name: Create comnent on new issue
on:  
  issues:
        types: [opened]
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo '${{ toJson(github.event)}}' | jq
        shell: bash
        
