name: hello simple workflwos
on:
  push:
     branches: [ "main" ]
  workflow_dispatch:

jobs:
  hello:
     runs-on: ubuntu-latest
     permissions:
      contents: write
     steps:
      - uses: actions/checkout@v4   #here @ can be anything branch , commit tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: hello work
        run: |
           echo "Hello Romit!!!" > index.txt
           git config user.email "automation@github_bot.com"
           git config user.name "github_bot"
           git add index.txt
           git commit -m "add greeting message"
           git push origin main
        shell: bash
  Goodbye:
     runs-on: ubuntu-latest
     steps:
      - name: Goodby world
        run: echo "Good bye world!!!"
        shell: bash

