name: hello simple workflwos
on:
  push:
     branches: [ "main" ]
  workflow_dispatch:

jobs:
  hello:
     runs-on: ubuntu-latest
     steps:
      - uses: action/checkou@v4   #here @ can be anything branch , commit tag
      - name: hello work
        run: echo "Hello Romit!!!"
        shell: bash
  Goodbye:
     runs-on: ubuntu-latest
     steps:
      - name: Goodby world
        run: echo "Good bye world!!!"
        shell: bash

